maintainer        'holysugar'
maintainer_email  'holysugar@gmail.com'
license           'MIT'
description       'holysugars osx install'
long_description  'holysugars osx install'
version           '0.1.0'
supports          'mac_os_x'

depends           'pivotal_workstation'
depends           'sprout-osx-settings'
depends           'sprout-osx-apps'
depends		  'sprout-holysugar'
